#!/usr/bin/env node

/**
 * DOCUVERSE SAAS - QUICK START WIZARD
 * 
 * Interactive setup wizard to get started in minutes
 */

const readline = require('readline');
const { execSync } = require('child_process');
const fs = require('fs');
const crypto = require('crypto');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

function exec(command) {
  try {
    execSync(command, { stdio: 'inherit' });
    return true;
  } catch (error) {
    return false;
  }
}

async function main() {
  console.log('\n🚀 Welcome to DocuVerse SaaS Setup Wizard!\n');
  console.log('This wizard will help you get started in under 5 minutes.\n');
  console.log('═'.repeat(60));
  
  // Step 1: Check if .env exists
  if (fs.existsSync('.env')) {
    console.log('\n⚠️  .env file already exists.');
    const overwrite = await question('Do you want to overwrite it? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }
  
  // Step 2: Choose database mode
  console.log('\n📊 Choose your database:');
  console.log('  1. SQLite (easiest, for local dev)');
  console.log('  2. Turso (recommended for production)');
  console.log('  3. MySQL (self-hosted)');
  console.log('  4. PlanetScale (cloud MySQL)');
  
  const dbChoice = await question('\nEnter choice (1-4) [1]: ');
  const dbMode = ['sqlite', 'turso', 'mysql', 'planetscale'][parseInt(dbChoice) - 1] || 'sqlite';
  
  let dbUrl = 'file:./dev.db';
  let tursoToken = '';
  
  if (dbMode === 'turso') {
    dbUrl = await question('Enter Turso database URL: ');
    tursoToken = await question('Enter Turso auth token: ');
  } else if (dbMode === 'mysql' || dbMode === 'planetscale') {
    dbUrl = await question('Enter MySQL connection string: ');
  }
  
  // Step 3: Generate auth secret
  console.log('\n🔐 Generating secure AUTH_SECRET...');
  const authSecret = crypto.randomBytes(32).toString('base64');
  console.log('✅ Generated!');
  
  // Step 4: Create .env file
  console.log('\n📝 Creating .env file...');
  
  let envContent = `# Generated by DocuVerse Setup Wizard

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
DATABASE_MODE=${dbMode}
DATABASE_URL="${dbUrl}"
${tursoToken ? `TURSO_AUTH_TOKEN="${tursoToken}"` : ''}

# =============================================================================
# NEXTAUTH.JS V5 CONFIGURATION
# =============================================================================
AUTH_SECRET="${authSecret}"
AUTH_URL="http://localhost:3000"
AUTH_TRUST_HOST=true

# =============================================================================
# APP CONFIGURATION
# =============================================================================
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_PUBLIC_APP_NAME="DocuVerse SaaS"

# =============================================================================
# OPTIONAL: Add these for full features
# =============================================================================
# STRIPE_SECRET_KEY=
# STRIPE_WEBHOOK_SECRET=
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
# TYPESENSE_HOST=localhost
# TYPESENSE_API_KEY=
# RESEND_API_KEY=
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
`;

  fs.writeFileSync('.env', envContent);
  console.log('✅ .env created!');
  
  // Step 5: Install dependencies
  console.log('\n📦 Checking dependencies...');
  if (!fs.existsSync('node_modules')) {
    console.log('Installing dependencies (this may take a few minutes)...');
    const installed = exec('npm install');
    if (!installed) {
      console.error('❌ Failed to install dependencies');
      rl.close();
      return;
    }
    console.log('✅ Dependencies installed!');
  } else {
    console.log('✅ Dependencies already installed!');
  }
  
  // Step 6: Setup database
  console.log('\n🗄️  Setting up database...');
  const pushed = exec('npm run db:push');
  if (!pushed) {
    console.error('❌ Failed to setup database');
    rl.close();
    return;
  }
  console.log('✅ Database schema created!');
  
  // Step 7: Seed database
  const seed = await question('\nSeed database with sample data? (Y/n): ');
  if (seed.toLowerCase() !== 'n') {
    console.log('Seeding database...');
    const seeded = exec('npm run db:seed');
    if (seeded) {
      console.log('✅ Database seeded!');
    }
  }
  
  // Final summary
  console.log('\n' + '═'.repeat(60));
  console.log('🎉 Setup Complete!\n');
  console.log('🚀 Start development server:');
  console.log('   npm run dev\n');
  console.log('🌐 Open browser:');
  console.log('   http://localhost:3000\n');
  
  if (seed.toLowerCase() !== 'n') {
    console.log('🔐 Login credentials:');
    console.log('   Email: admin@docuverse.id');
    console.log('   Password: ChangeMeInProduction123!\n');
  }
  
  console.log('📚 Documentation:');
  console.log('   README.md - Overview');
  console.log('   SETUP.md - Detailed setup guide');
  console.log('   DEPLOYMENT.md - Production deployment\n');
  
  console.log('═'.repeat(60));
  
  rl.close();
}

main().catch(console.error);
